@extends('user-site.main')
@section('content-layout')
    <div id="content-layout">
        <h1 class="hpage">Terms and Conditions of Use</h1>
        <div class="container">
            <div class="content-holder">
                <div class="content-box">
                    <div class="box-body">
                        <div class="block-text">
                            <p><strong>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE ACCESSING OR USING THIS WEB SITE.</strong></p>
                            <p class="hmb mto"><strong>ACCEPTANCE OF TERMS OF USE</strong></p>
                            <p>BY ACCESSING THIS WEB SITE, YOU ARE AGREEING TO BE BOUND BY THESE TERMS OF USE, ALL APPLICABLE LAWS AND REGULATIONS, AND AGREE THAT YOU ARE RESPONSIBLE FOR COMPLIANCE WITH ANY APPLICABLE LOCAL LAWS. IF YOU ARE USING THIS WEB SITE ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY TO THESE TERMS OF USE, IN WHICH CASE THE TERMS "YOU" OR "YOUR" SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT UNDERSTAND AND AGREE WITH THESE TERMS OF USE, YOU SHOULD SEEK LEGAL COUNSEL, AND NOT USE THIS SITE OR ITS SERVICES.</p>
                            <p class="hmb mto"><strong>TERMS OF USE</strong></p>
                            <p>Your use of the Web Site or any of its Content and services made available through the Web Site constitutes Your agreement to the following terms and conditions:</p>
                            <ol class="plain">
                                <li>
                                    <p class="hmb"><strong>Definitions</strong></p>
                                    <ul class="plain">
                                        <li><strong>"Affiliate" </strong>means, with respect to a party, any entity which directly or indirectly controls, is controlled by, or is under common control with such party.</li>
                                        <li><strong>"Agreement" </strong>means this Terms and Conditions of Use.</li>
                                        <li><strong>"Web Site" </strong>means the hosted, on-demand, Web-based on-line service provided by MyTeachingStation.com, including updates from time to time.</li>
                                        <li><strong>"Malicious Code" </strong>means viruses, worms, time bombs, Trojan horses and other harmful, disruptive, or destructive files, code, scripts, agents or programs.</li>
                                        <li><strong>"User" </strong>means You and Your employees, agents, contractors, consultants or any other individuals and/or end users who are authorized by You to access and use the Web Site and/or whose information is stored on the Web Site.</li>
                                        <li><strong>"MyTeachingStation.com" </strong>means My Teaching Station LLC, a Florida Limited Liability Company. You may contact MyTeachingStation.com via our Web Site.</li>
                                        <li><strong>"You" or "Your"</strong> means the individual, company, or other legal entity for which You are accepting this Terms and Conditions of Use.</li>
                                        <li><strong>"Content" </strong>means any content on this Web Site, including the text, graphics, images, information, and other materials contained on the Web Site.</li>
                                        <li><strong>"Your Data" </strong>means without limitation any and all data and textual information submitted to or through the Web Site by You. You are required, at Your own expense, to ensure that all such text and data meets all local, state, and federal security and confidentiality requirements before its entry into the Web Site, storage and use in the database(s) used for the Web Site, and for its eventual display and/or use on any screen or page of the Web Site.</li>
                                    </ul>
                                </li>
                                <li>
                                    <p class="hmb"><strong>User Conduct</strong></p>
                                    <p>You are responsible for all activities conducted under Your User login and for Your compliance with this Terms and Conditions of Use. You shall use the Web Site and its Content solely for personal, noncommercial, informational purposes, in compliance with applicable law, and shall not:</p>
                                    <ul class="plain">
                                        <li>Resell, sublicense, lease, time-share or otherwise make the Web Site available to any third party;</li>
                                        <li>Modify, copy or create derivative works based on the Web Site or its Content, including photocopying and recording, except that MyTeachingStation.com authorizes You to view and print one copy per child or person of free Content that is available on the Web Site (such as articles, worksheets or papers);</li>
                                        <li>Republish, upload, post, transmit or distribute Content from the Web Site to online message boards, newsgroups, chat rooms, bulletin boards, or in other any manner, without our prior written permission. Modification of the Content or use of the Content for any purpose other than Your own personal, non-commercial use is a violation of our copyright and other proprietary rights, and may subject You to legal liability.</li>
                                        <li>Remove any copyright, trademark, or other proprietary notations from the Content;</li>
                                        <li>Attempt to gain unauthorized access to, or disrupt the integrity or performance of, the Web Site or the data contained therein, including, without limitation, by means of "hacking" or defacing any portion of the Web Site;</li>
                                        <li>Post, disseminate, or transmit Malicious Code;</li>
                                        <li>Interfere with, disrupt, or harm in any way the Web Site or servers or networks connected to the Web Site;</li>
                                        <li>Use the Web Site for any unlawful or illegal purpose or in violation of any of the rules herein;</li>
                                        <li>Post, disseminate, or transmit any Content You do not have the right to post, disseminate, or transmit;</li>
                                        <li>Post, disseminate, or transmit any unauthorized advertising, promotional materials, chain letters, spam, junk mail, or any other type of unsolicited mass e-mail to people or entities that have not agreed to be part of such mailings;</li>
                                        <li>Post, disseminate, or transmit any Content that is or which we consider, in our sole discretion, unlawful, harassing, defamatory, abusive, threatening, vulgar, obscene, pornographic, harmful, tortuous, libelous, racist, violent or otherwise objectionable;</li>
                                        <li>Electronically stalk or otherwise harass another user of our Web Site;</li>
                                        <li>Post or disclose any personally identifying information or private information about children or any third parties without their consent (or their parent's consent in case of a child under 13 years of age);</li>
                                        <li>Impersonate any person or entity; falsely state or otherwise misrepresent Your affiliation with any person or entity; intentionally omit, delete, forge, or misrepresent transmission information; or otherwise manipulate identifiers to disguise the origin of any Content transmitted through the Web Site;</li>
                                        <li>Express or imply that any statements You make are endorsed by us, without our prior written consent;</li>
                                        <li>Collect information about visitors to the Web Site without their express consent or store personal data about other users;.</li>
                                        <li>Transfer the Content to another person, "Frame" or "mirror" any part of the Web Site or its Content without our prior written authorization;</li>
                                        <li>Reverse engineer, decompile, disassemble, modify, adapt, sublicense, translate or sell any portion of the Web Site or its Content;</li>
                                        <li>Use any robot, spider, site search/retrieval application, or other manual or automatic device or process to download, retrieve, index, "data mine," or in any way reproduce or circumvent the navigational structure or presentation of the Web Site or its contents;</li>
                                        <li>Access the Web Site for the purpose of building a competitive product or service or copying its features or user interface;</li>
                                        <li>Use the Web Site, or permit it to be used, for purposes of product evaluation, benchmarking or other comparative analysis intended for publication without prior written consent from MyTeachingStation.com;</li>
                                        <li>Permit access to the Web Site by a direct competitor of MyTeachingStation.com, or</li>
                                        <li>Allow any User under the age of 18 to access or use the Web Site.</li>
                                    </ul>
                                    <p>&nbsp;</p>
                                    <p>Nothing contained on this Web Site should be construed as granting, by implication, estoppel, or otherwise, any license or right to use this Web Site or any information or documents displayed on the Web Site, through the use of framing or otherwise, except: (a) as expressly permitted by these terms and conditions; or (b) with the prior written permission of MyTeachingStation.com or such third party that may own the trademark or copyright of material displayed on this Web Site. If You are interested in reprinting, republishing or distributing content from MyTeachingStation.com, please contact us via our Web Site.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Terms of Use Modifications</strong></p>
                                    <p>MyTeachingStation.com reserves the right to modify or replace this Agreement at any time without prior notice. For this reason, we encourage You to review this Agreement periodically for changes. Any changes will be effective immediately upon posting the revised version on the Web Site. Your continued use of the Web Site following the posting of any changes to this Agreement will constitute Your acceptance of such changes. By using this&nbsp;<span style="background-color: rgb(245, 246, 245);">Web Site,</span>&nbsp;Yagree to be bound by the current version of these Terms and Conditions of Use. If You do not agree to the changes, You must immediately stop using the Web Site.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Site Membership</strong></p>
                                    <p>MyTeachingStation.com reserves the right to refuse registration, or to refuse or limit access to the Web Site or any features, to anyone in its sole discretion. You will provide accurate, current and complete information in any registration or other account-related forms provided on the Web Site and agree to maintain the security of Your username(s) and password(s). You will maintain and promptly update Your Information to keep it accurate, current and complete. YOU UNDERSTAND THAT ANY PERSON WITH YOUR USERNAME(S) AND PASSWORD(S) MAY BE ABLE TO ACCESS YOUR ACCOUNT (INCLUDING YOUR INFORMATION, TRANSACTION INFORMATION, AND OTHER USER DATA YOU OR OTHERS HAVE PROVIDED TO MYTEACHINGSTATION.COM (SOME OF WHICH YOU MAY CONSIDER CONFIDENTIAL IN NATURE). YOU ACCEPT ALL RISKS OF UNAUTHORIZED ACCESS TO THE WEB SITE BASED ON THE SHARING OR LOSS OF A USERNAME AND PASSWORD. You will promptly notify MyTeachingStation.com if You discover or otherwise suspect any security breaches related to the Web Site, including any unauthorized use or disclosure of a username or password. You understand and agree that MyTeachingStation.com may, under certain circumstances and without prior notice to You, terminate Your access to and use of the Web Site. Cause for such termination shall include, but not be limited to, (a) breaches or violations of the Agreement or other agreements or guidelines, (b) requests by law enforcement or other government or regulatory authorities, or (c) technical difficulties.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Features and Links to Other Sites</strong></p>
                                    <p>There may be times when You may be able&nbsp;to gain access to other web sites and/or Internet related content that is not owned, maintained, or controlled by MyTeachingStation.com (and which may or may not be part of the Web Site). Such additional information and/or content may be available via hyperlink from the Web Site, or it may be contained within and integrated with Content provided by MyTeachingStation.com. MyTeachingStation.com assumes no responsibility for any material outside the Web Site that may be accessed in this manner.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>MyTeachingStation.com Proprietary Rights</strong></p>
                                    <p>All information, content, instructions and services provided by MyTeachingStation.com, its owners, officers, investors, employees, agents, and authorized representatives on the Web Site is owned by or licensed to MyTeachingStation.com (the "Content"). MyTeachingStation.com and its licensors retain all proprietary rights to the Content.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Warranty Disclaimers</strong></p>
                                    <p>MyTeachingStation.com makes no guarantee or warranty as to the accuracy or completeness of the Web Site or the Content and the Web Site, and the Content is provided "AS-IS" and "AS-AVAILABLE". Neither MyTeachingStation.com nor any of its licensors shall be liable to You or anyone else for any damages arising from or relating to any inaccuracy, error or omission in the Web Site or the Content. By using this Web Site, You assume the risk that the information on this Web Site and its Content may be incomplete, inaccurate, out of date, or may not meet Your needs and requirements. The Content provided by this Web Site does not constitute the rendering of medical, health, legal or other professional advice or services. Always seek the advice of Your physician or other qualified health provider with questions You may have regarding any medical conditions. The Content should not be relied upon or used as a substitute for consultation with physicians, qualified health professionals, lawyers or other professional advisors. Reliance on any Content provided on this Web Site, whether by us or visitors to this Web Site is solely at Your own risk. We do not recommend or endorse any specific tests, physicians, products, procedures, opinions or other information that may be mentioned on this Web Site.</p>
                                    <p>TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, MYTEACHINGSTATION.COM, ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, SUPPLIERS, ADVERTISERS, AND AGENTS DISCLAIM ANY AND ALL WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, AND ALL WARRANTIES RELATING TO THE ADEQUACY, ACCURACY OR COMPLETENESS OF ANY INFORMATION ON OUR WEB SITES.</p>
                                    <p>Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusions may not apply to you.</p>
                                    <p>YOU ACKNOWLEDGE THAT YOU ARE RESPONSIBLE FOR OBTAINING AND MAINTAINING ALL TELEPHONE, COMPUTER HARDWARE AND OTHER EQUIPMENT NEEDED TO ACCESS AND USE OUR WEB SITES, AND ALL CHARGES RELATED THERETO. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE WEB SITE AND YOUR RELIANCE THEREON. NO OPINION, ADVICE, OR STATEMENT OF MYTEACHINGSTATION.COM OR ITS AFFILIATES, SUPPLIERS, AGENTS, MEMBERS, OR VISITORS, WHETHER MADE ON THE WEB SITE OR OTHERWISE, SHALL CREATE ANY WARRANTY. YOUR USE OF THE WEB SITE, THE CONTENT CONTAINED HEREIN, AND ANY MATERIALS PROVIDED THROUGH THE WEB SITE, ARE ENTIRELY AT YOUR OWN RISK.</p>
                                    <p>A possibility exists that the Web Site could include inaccuracies or errors, or Content that violate this Agreement. Additionally, a possibility exists that unauthorized alterations could be made to the Web Site by third parties. Although we attempt to ensure the integrity of the Web Site and other products and services, we make no guarantees as to the completeness or correctness of the Content. In the event that such a situation arises, please contact us via our Web Site with, if possible, a description of the Content to be checked and the location (URL) where such Content can be found on our Web Site, if applicable, as well as information sufficient to enable us to contact you. We will try to address your concerns as soon as reasonably practicable.</p>
                                    <p>The accuracy of information supplied by You and other users is not within the control of MyTeachingStation.com, and MyTeachingStation.com does not certify that it has verified any information, file, or other information entered into the Web Site database or available on this Web Site. MyTeachingStation.com has no obligation to screen or edit information that is posted or shared by You or other users of the Web Site, and we reserve the right (without notice) to remove any information found on the Web Site that MyTeachingStation.com finds to be objectionable. Our policy with respect to the collection and use of Your personal information is set forth in our Privacy Statement.</p>
                                    <p>MyTeachingStation.com has NO authority or control over the operation or performance of any portion of the Internet including other Internet sites to which this Web Site may be linked or from which this Web Site may be accessed. You acknowledge that in any computer system and any network of computer systems there is certain to be downtime due to mechanical, telecommunication, software, hardware and third party vendor failures during which MyTeachingStation.com will be unable to provide access to this Web Site. MyTeachingStation.com cannot predict or control when such downtime may occur and cannot control the duration of such "downtime." We may alter, suspend, or discontinue this Web Site, or any Content, at any time for any reason, without notice or cost. We may also elect, at any time upon notice, to begin to impose fees or charges for access or use of this Web Site.</p>
                                    <p>You understand and agree that the Internet is inherently unreliable and subject to breaches of security and the transmission of Malicious Code that can cause harm to Your computer system(s). Therefore, MyTeachingStation.com cannot be responsible for the integrity of any information, file or another posting available on, sent to, or received from or through this Web Site. MyTeachingStation.com shall not be liable to You or any third parties for any damage to Your computer from the use of this Web Site or for Malicious Code Your computer may receive by accessing this Web Site.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Privacy Statement</strong></p>
                                    By accessing the Web Site, you also expressly accept the Web Site’s privacy statement. A complete statement of our current privacy statement can be found at www.theteachingstation.com/privacy-statement. The Web Site terms of use and privacy statement are expressly incorporated into this Agreement by this reference.
                                    <p>You acknowledge that all discussion for votes, ratings, comments and/or other message or communication facilities are public and not private communications, and that, therefore, others may read Your communications without Your knowledge. MyTeachingStation.com does not control or endorse the content, messages or information found in any Community, and, therefore, MyTeachingStation.com specifically disclaims any liability concerning the Communities and any actions resulting from Your participation in any Community, including any objectionable content. Generally, any communication which You post to MyTeachingStation.com is considered to be non-confidential. If particular web pages permit the submission of communications that will be treated by MyTeachingStation.com as confidential, that fact will be stated on those pages. By posting comments, lessons or worksheet requests, messages or other information on the Web Site, You grant MyTeachingStation.com the right to use such comments, messages or information for promotions, advertising, market research or any other lawful purpose. For more information see MyTeachingStation.com's Privacy Statement as noted above.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Sales Policy</strong></p>
                                    The purchase and use of MyTeachingStation.com products are subject to additional terms and conditions found in the <a href="{{ route('policy') }}">Sales Policy</a> page.
                                </li>
                                <li>
                                    <p class="hmb"><strong>Monitoring</strong></p>
                                    <p>Access to this Web Site is monitored. The requesting URLs, the machine originating the request, and the time of the request are logged for access statistics and security purposes. Your use of this Web Site constitutes consent to such monitoring.</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Indemnification</strong></p>
                                    <p>By using this Web Site, You agree to indemnify, hold harmless and defend MyTeachingStation.com from any claims, damages, losses, liabilities and all costs and expenses of defense, including but not limited to attorneys' fees, resulting directly or indirectly from Your use of this Web Site. Furthermore, You agree to indemnify, hold harmless and defend MyTeachingStation.com from any damages, losses, costs and expenses (including reasonable attorneys' fees) it suffers which arise from or relate to Your breach of these Terms and Conditions of Use. Your sole and exclusive remedy for any breach of this agreement by MyTeachingStation.com shall be a refund of the fees paid to use the Web Site (if any).</p>
                                </li>
                                <li>
                                    <p class="hmb"><strong>Miscellaneous</strong></p>
                                    <p>The Web Site and certain of the Content is copyright material and cannot be copied, distributed, or reproduced in any manner without the express written permission of MyTeachingStation.com - all rights reserved.</p>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
@endsection
